### ISSUE TITLE
Setting maxLogLines: 0 in configuration is ignored.

### ISSUE THREAD

**Issue by jamesearl** [whyboris/karma-helpful-reporter#20]
Actually seems like all of the config block in my karma.conf.js is ignored, but the given one `maxLogLines` is the one that I'm trying to use.

**Comment by whyboris** [comment]
Sorry for the delay in my response. Zero isn't an acceptable value because I hadn't foreseen someone wanting that. My code is
```

if (maxLogLines) {
    maxLines = maxLogLines;
}
```
Zero is falsy.
Could `suppressErrorReport` be equivalent to what you are looking for?
